name: nbval

on:
  workflow_dispatch:
  pull_request:
    branches:
    - 'main'
    paths:
    - 'notebooks/**.ipynb'
    - 'notebooks/**.py'
    - 'requirements.txt'
    - '.github/workflows/nbval.yml'
  push:
    branches:
    - 'main'
    paths:
    - 'notebooks/**.ipynb'
    - 'notebooks/**.py'
    - 'requirements.txt'
    - '.github/workflows/nbval.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    #defaults:
    #  run:
    #    shell: bash
    #    working-directory: ./openvino-monai/medmnist
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python: [3.7, 3.8]
    steps:
    - name: Cache Pip
      id: cachepip
      uses: actions/cache@v2
      with:
        path: |
          pipcache
        key: cache-pip-2021.4.2-1119-${{ matrix.os }}-${{ matrix.python }}
 
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Cache openvino packages
      if: steps.cachepip.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        mkdir pipcache
        python -m pip install --cache-dir pipcache --no-deps openvino openvino-dev nncf
        cp -r pipcache pipcache_openvino
        python -m pip uninstall -y openvino openvino-dev nncf
 
    - name: install jupyterlab nbval
      run: |
        python -m pip install nbval
        python -m pip install -r medmnist/requirements.txt --cache-dir pipcache
    - name: Create pipcache directory
      if: steps.cachepip.outputs.cache-hit != 'true'
      run: |
        mv pipcache pipcache_full
        mv pipcache_openvino pipcache
    - name: Analysing with nbval
      run: |
        python -m pytest -x --nbval --current-env --durations 10 .

#    - name: papermill
#      run: |
#        bash papermill_medmnist.sh
#    - name: ls
#      run: |
#        ls -lR
#    - name: Archive html
#      uses: actions/upload-artifact@v2
#      with:
#        name: medmnist_monai_notebooks
#        path: ./medmnist/medmnist_monai_notebooks
 
